window.MONTHLY_SPENDING_DATA={month:'2026-08',card:'Cartão Itau Platinum',invoiceTotal:7631.96,installmentsTotal:2935.63,newSpendingTotal:4696.33,categories:[{name:'Alimentação',value:2218.92},{name:'Veículos',value:1368.02},{name:'Diversos / Outros',value:499.26},{name:'Saúde',value:300.79},{name:'Vestuário',value:184.59},{name:'Educação',value:117.76},{name:'Turismo / Lazer',value:56},{name:'Moradia',value:5},{name:'Tarifas / Ajustes',value:-54.01}],transactions:[
{date:'26/06',description:'PETIZ IMPRESSOES & COMU',value:-0.22,category:'Diversos / Outros'},
{date:'03/07',description:'SUCO FRUTAO -CT',value:19.90,category:'Alimentação'},
{date:'04/07',description:'MP*ANCORABUR-CT',value:5,category:'Alimentação'},
{date:'04/07',description:'REI DO TRIGO-CT',value:65.50,category:'Alimentação'},
{date:'04/07',description:'AIRTON JORGE-CT OLIVEI',value:8.50,category:'Alimentação'},
{date:'04/07',description:'MP*ADRIANOME-CT OS',value:95,category:'Diversos / Outros'},
{date:'04/07',description:'MERCADO SAO -CT',value:30.96,category:'Alimentação'},
{date:'04/07',description:'LUCAS GAS -CT',value:13,category:'Alimentação'},
{date:'04/07',description:'EMPORIO CASA-CT CARNE',value:59.61,category:'Alimentação'},
{date:'05/07',description:'CONVENIENCIA-CT UJO',value:15.50,category:'Alimentação'},
{date:'05/07',description:'FORT ATACADI-CT 470',value:83.91,category:'Alimentação'},
{date:'05/07',description:'ALIMENTOS PA-CT EIRO',value:92,category:'Alimentação'},
{date:'05/07',description:'FARMACIA MAI-CT PULAR',value:38.50,category:'Saúde'},
{date:'06/07',description:'CHAVEIRO ANT-CT TO',value:110,category:'Diversos / Outros'},
{date:'06/07',description:'LOTUS COMERCIO DE COM',value:200,category:'Veículos'},
{date:'07/07',description:'ESPETINHO DO-CT ANA',value:40,category:'Alimentação'},
{date:'07/07',description:'POSTO LR -CT',value:53.35,category:'Veículos'},
{date:'09/07',description:'JadilsonQuad-CT',value:36.48,category:'Alimentação'},
{date:'10/07',description:'NORTE SUL ES-CT ONAME',value:23,category:'Veículos'},
{date:'10/07',description:'NORTE SUL -CT',value:10,category:'Turismo / Lazer'},
{date:'10/07',description:'NORTE SUL -CT',value:36,category:'Turismo / Lazer'},
{date:'11/07',description:'F4 -CT',value:11,category:'Veículos'},
{date:'11/07',description:'FORT ATACADI-CT 470',value:127.44,category:'Alimentação'},
{date:'11/07',description:'MERCADO MIST-CT UNIOR',value:27.94,category:'Alimentação'},
{date:'11/07',description:'RosimariHimo-CT',value:64,category:'Alimentação'},
{date:'11/07',description:'FredConvenie-CT',value:5.25,category:'Alimentação'},
{date:'12/07',description:'POSTO MIRAND-CT',value:194.03,category:'Veículos'},
{date:'12/07',description:'CHIPAS MAXIM-CT',value:8.50,category:'Alimentação'},
{date:'12/07',description:'46487598Mary-CT',value:90,category:'Veículos'},
{date:'13/07',description:'NORMAN PERFU-CT BOX278',value:45,category:'Diversos / Outros'},
{date:'13/07',description:'COMPER 245 -CT',value:7.99,category:'Alimentação'},
{date:'13/07',description:'POSTO MIRAND-CT',value:57,category:'Veículos'},
{date:'14/07',description:'EMPORIO CASA-CT CARNE',value:44.21,category:'Alimentação'},
{date:'15/07',description:'SORVETES E C-CT',value:11.74,category:'Alimentação'},
{date:'15/07',description:'DROGASIL 487-CT',value:110.83,category:'Saúde'},
{date:'16/07',description:'SERTAO COMER-CT DE EQ',value:66.90,category:'Alimentação'},
{date:'16/07',description:'LUCAS GAS -CT',value:9.50,category:'Alimentação'},
{date:'17/07',description:'TAMANDARE BE-CT ISTRIB',value:13.50,category:'Alimentação'},
{date:'17/07',description:'ZP*REBECA MA-CT 5',value:12,category:'Alimentação'},
{date:'18/07',description:'BUTEKO FESTA-CT',value:10.80,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VIDA VILA G',value:10,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VIDA VILA G',value:20,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VIDA VILA G',value:10,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VID-CT ILA G',value:25,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VIDA VILA G',value:15,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VID-CT ILA G',value:3,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VID-CT ILA G',value:6,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VID-CT ILA G',value:8,category:'Diversos / Outros'},
{date:'18/07',description:'VERBO DA VIDA VILA G',value:15,category:'Diversos / Outros'},
{date:'18/07',description:'CTBRB CGR VI-CT LORIA',value:10,category:'Alimentação'},
{date:'18/07',description:'CACAU SHOW -CT',value:35,category:'Alimentação'},
{date:'18/07',description:'BONATTO E BO-CT O-CS',value:47.39,category:'Alimentação'},
{date:'18/07',description:'MERCADO SAO -CT',value:4.22,category:'Alimentação'},
{date:'18/07',description:'EDINALDO -CT',value:65,category:'Diversos / Outros'},
{date:'18/07',description:'RDM ESTACION-CT TO',value:3,category:'Veículos'},
{date:'18/07',description:'EMBALLAR -CT',value:2.50,category:'Alimentação'},
{date:'18/07',description:'EMPORIO CASA-CT CARNE',value:62.65,category:'Alimentação'},
{date:'19/07',description:'CHIPAS MAXIM-CT ANDA',value:8,category:'Alimentação'},
{date:'19/07',description:'FORT ATACADI-CT 77',value:121.21,category:'Alimentação'},
{date:'19/07',description:'LOJAS AMERIC-CT 1239',value:45.96,category:'Vestuário'},
{date:'19/07',description:'SHEKEL PARK -CT',value:15,category:'Veículos'},
{date:'20/07',description:'DROGASIL 426-CT',value:25.49,category:'Saúde'},
{date:'20/07',description:'AUTO POSTO S-CT ORGE',value:190,category:'Veículos'},
{date:'20/07',description:'LETRAS DU CA-CT EARA',value:38.50,category:'Educação'},
{date:'20/07',description:'MERCADO PAG -CT LTDA',value:22.07,category:'Alimentação'},
{date:'21/07',description:'REI DO TRIGO-CT',value:33.50,category:'Alimentação'},
{date:'21/07',description:'GislaineRodr-CT s',value:67,category:'Diversos / Outros'},
{date:'21/07',description:'54648228Gize-CT',value:10,category:'Veículos'},
{date:'22/07',description:'POSTO MODELO-CT',value:10.50,category:'Veículos'},
{date:'22/07',description:'POSTO LR -CT',value:54.19,category:'Veículos'},
{date:'22/07',description:'MariaEduarda-CT a',value:47,category:'Alimentação'},
{date:'23/07',description:'EMPORIO CASA-CT CARNE',value:15.24,category:'Alimentação'},
{date:'24/07',description:'JOAO BATISTA-CT EIRA DA',value:30,category:'Saúde'},
{date:'24/07',description:'BOX 26/27 PJ-CT',value:70,category:'Alimentação'},
{date:'24/07',description:'PAF UTILIDAD-CT PRESEN',value:14.99,category:'Saúde'},
{date:'24/07',description:'SandroMarian-CT',value:24,category:'Vestuário'},
{date:'25/07',description:'FORT ATACADI-CT 76',value:50.89,category:'Alimentação'},
{date:'25/07',description:'MERCADO SAO -CT',value:18.26,category:'Alimentação'},
{date:'25/07',description:'LUCAS GAS -CT',value:52.99,category:'Alimentação'},
{date:'25/07',description:'POSTO SAITO -CT',value:51.60,category:'Veículos'},
{date:'25/07',description:'FogoEBrasa -CT',value:25,category:'Alimentação'},
{date:'25/07',description:'MauroRamires-CT',value:12,category:'Diversos / Outros'},
{date:'25/07',description:'MP *BRUNOJOR-CT L',value:12,category:'Alimentação'},
{date:'25/07',description:'MP *BRUNOJOR-CT L',value:12,category:'Alimentação'},
{date:'25/07',description:'BS MARCENARI-CT',value:5,category:'Moradia'},
{date:'25/07',description:'MP *BRUNOJOR-CT L',value:12,category:'Alimentação'},
{date:'26/07',description:'MP *BRUNOJOR-CT L',value:5,category:'Alimentação'},
{date:'26/07',description:'ASSADOS CAFE-CT',value:57,category:'Alimentação'},
{date:'26/07',description:'MP*NUNES -CT',value:8.90,category:'Alimentação'},
{date:'26/07',description:'FORT ATACADI-CT 470',value:97.66,category:'Alimentação'},
{date:'27/07',description:'MP*TALISSEAP-CT',value:15.20,category:'Alimentação'},
{date:'27/07',description:'EMPORIO CASA-CT CARNE',value:45.26,category:'Alimentação'},
{date:'28/07',description:'COMPER 245 -CT',value:12.98,category:'Alimentação'},
{date:'28/07',description:'64583017Davi-CT',value:49.90,category:'Alimentação'},
{date:'30/07',description:'POSTO SEARA -CT',value:61.45,category:'Veículos'},
{date:'30/07',description:'Null -CT',value:65.50,category:'Veículos'},
{date:'31/07',description:'MP*ANCORABUR-CT',value:5,category:'Alimentação'},
{date:'31/07',description:'POSTO SAITO -CT',value:192,category:'Veículos'},
{date:'31/07',description:'LUCAS GAS -CT',value:39.22,category:'Alimentação'},
{date:'31/07',description:'SandroMarian-CT',value:24,category:'Alimentação'},
{date:'02/08',description:'FORT ATACADI-CT 77',value:24.15,category:'Alimentação'},
{date:'02/08',description:'SHEKEL PARK -CT',value:15,category:'Veículos'},
{date:'02/08',description:'BOX MANIA',value:27.99,category:'Diversos / Outros'},
{date:'05/07',description:'NUNES SUPERM-CT UANAND',value:44.80,category:'Alimentação'},
{date:'06/07',description:'COLEGIO VIDA-CT IZ',value:7.50,category:'Educação'},
{date:'07/07',description:'MARAVILHAS P-CT UM LTDA',value:25.44,category:'Diversos / Outros'},
{date:'07/07',description:'FORT ATACADI-CT 470',value:62.96,category:'Alimentação'},
{date:'07/07',description:'COLE VIDA FE-CT',value:12,category:'Educação'},
{date:'07/07',description:'BamboleKidsM-CT',value:10,category:'Vestuário'},
{date:'08/07',description:'DROGASIL 415-CT',value:51.63,category:'Saúde'},
{date:'11/07',description:'MP*STUFFHSC -CT',value:55,category:'Vestuário'},
{date:'12/07',description:'PERFORMANCE -CT GE F',value:5,category:'Diversos / Outros'},
{date:'16/07',description:'COLEGIO VIDA-CT IZ',value:7.50,category:'Educação'},
{date:'17/07',description:'COLEGIO VIDA-CT IZ',value:6,category:'Educação'},
{date:'20/07',description:'COMPER 72 -CT',value:36.44,category:'Alimentação'},
{date:'23/07',description:'FORT ATACADI-CT 470',value:85.97,category:'Alimentação'},
{date:'29/07',description:'FORT ATACADI-CT 470',value:139.07,category:'Alimentação'},
{date:'30/07',description:'NUNES SUPERM-CT UANAND',value:31.04,category:'Alimentação'},
{date:'02/08',description:'NUNES SUPERM-CT UANAND',value:34.01,category:'Alimentação'},
{date:'03/08',description:'ENVIO MENS.AUTOMATICA',value:7.99,category:'Tarifas / Ajustes'},
{date:'03/08',description:'ESTORNO DE ANUIDADE DIF',value:-62,category:'Tarifas / Ajustes'}]};
